import { requireAdmin } from "@/lib/auth";
import { canManage, canManageOrganizationSettings, canManageProgramPayments, getOrganizationEmailSettings, listAdminProgramsForSession } from "@/lib/admin-access";
import { saveMyProgramStripeAccount, saveOrganizationEmailSettings, saveProgramNotificationEmails, updateMyPassword } from "../actions";

export const metadata = { title: "Settings" };

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ password?: string; stripe?: string; email?: string }> }) {
  const session = await requireAdmin();
  const [status, programs, emailSettings] = await Promise.all([searchParams, listAdminProgramsForSession(session), getOrganizationEmailSettings(session.organizationId)]);
  const boosterPrograms = programs.filter((program) => program.type === "booster_club");

  return <div className="grid max-w-3xl gap-6">
    {canManageOrganizationSettings(session) ? <form action={saveOrganizationEmailSettings} className="wildcat-card grid gap-4 rounded-sm p-5">
      <div><p className="eyebrow">Organization delivery</p><h1 className="text-3xl font-black uppercase text-[var(--ink)]">Email settings</h1><p className="mt-1 text-sm font-medium text-[var(--muted)]">These settings replace hard-coded notification recipients. The sender must stay on the verified WHSSignups domain.</p></div>
      {status.email === "organization" ? <p role="status" className="rounded-sm bg-[#f1fbf3] p-3 font-black text-[#225c2d]">Organization email settings saved.</p> : null}
      <div className="grid gap-4 sm:grid-cols-2">
        <label className="grid gap-1.5"><span className="font-black uppercase tracking-wide">Sender display name</span><input name="senderName" className="field" defaultValue={emailSettings.senderName} required /></label>
        <label className="grid gap-1.5"><span className="font-black uppercase tracking-wide">Sender address</span><input name="senderAddress" type="email" className="field" defaultValue={emailSettings.senderAddress || "noreply@whssignups.com"} required /></label>
        <label className="grid gap-1.5"><span className="font-black uppercase tracking-wide">Public contact email</span><input name="contactEmail" type="email" className="field" defaultValue={emailSettings.contactEmail} required /></label>
        <label className="grid gap-1.5"><span className="font-black uppercase tracking-wide">Default reply-to email</span><input name="replyToEmail" type="email" className="field" defaultValue={emailSettings.replyToEmail || emailSettings.contactEmail} required /></label>
      </div>
      <label className="grid gap-1.5"><span className="font-black uppercase tracking-wide">Default notification recipients</span><textarea name="defaultNotificationEmails" className="field" rows={3} defaultValue={emailSettings.defaultNotificationEmails.join("\n")} placeholder={"president@example.com\nvolunteers@example.com"} /><small className="font-medium text-[var(--muted)]">One per line, or separate addresses with commas. These receive organization-wide copies in addition to assigned admins and event owners.</small></label>
      <button className="min-h-12 rounded-sm bg-[var(--maroon)] px-5 font-black uppercase tracking-wide text-white hover:bg-[var(--maroon-dark)]">Save email settings</button>
    </form> : null}

    {canManage(session) && programs.length > 0 ? <section className="wildcat-card grid gap-4 rounded-sm p-5">
      <div><p className="eyebrow">Program delivery</p><h2 className="text-2xl font-black uppercase text-[var(--ink)]">Notification recipients</h2><p className="mt-1 text-sm font-medium text-[var(--muted)]">Set the board members or volunteer chairs who receive every signup and cancellation for each assigned program.</p></div>
      {status.email === "program" ? <p role="status" className="rounded-sm bg-[#f1fbf3] p-3 font-black text-[#225c2d]">Program notification recipients saved.</p> : null}
      <div className="grid gap-3">{programs.map((program) => <form action={saveProgramNotificationEmails} key={program.id} className="grid gap-3 rounded-sm border border-[var(--border)] p-4"><input type="hidden" name="programId" value={program.id}/><strong className="uppercase text-[var(--ink)]">{program.name}</strong><label className="grid gap-1"><span className="text-sm font-black uppercase">Recipient emails</span><textarea name="notificationEmails" className="field" rows={2} defaultValue={(program.notificationEmails ?? []).join("\n")} placeholder="volunteers@example.com" /></label><button className="min-h-11 justify-self-start rounded-sm bg-[var(--maroon)] px-4 font-black uppercase text-white">Save recipients</button></form>)}</div>
    </section> : null}

    {canManageProgramPayments(session) && boosterPrograms.length > 0 ? <section className="wildcat-card grid gap-4 rounded-sm p-5"><div><p className="eyebrow">Payment routing</p><h2 className="text-2xl font-black uppercase text-[var(--ink)]">Connected Stripe accounts</h2><p className="mt-1 text-sm font-medium text-[var(--muted)]">Only enter an account connected to the WHSSignups Stripe platform. Each account can belong to one Booster Club.</p></div>{status.stripe ? <p role="status" className="rounded-sm bg-[#f1fbf3] p-3 font-black text-[#225c2d]">{status.stripe === "connected" ? "Stripe account verified and ready for payments." : status.stripe === "pending" ? "Stripe account verified. Stripe still needs to enable charges before checkout can use it." : "Stripe account assignment removed."}</p> : null}<div className="grid gap-3">{boosterPrograms.map((program) => <form action={saveMyProgramStripeAccount} key={program.id} className="grid gap-3 rounded-sm border border-[var(--border)] p-4"><input type="hidden" name="programId" value={program.id}/><div className="flex flex-wrap items-center justify-between gap-2"><strong className="uppercase text-[var(--ink)]">{program.name}</strong><span className={`rounded-full px-3 py-1 text-xs font-black uppercase ${program.stripeAccountId && program.stripeChargesEnabled ? "bg-[#e8f6eb] text-[#225c2d]" : "bg-[#fff4d8] text-[var(--maroon-dark)]"}`}>{program.stripeAccountId ? program.stripeChargesEnabled ? "Ready" : "Pending Stripe" : "Using test platform"}</span></div><label className="grid gap-1"><span className="text-sm font-black uppercase">Stripe account ID</span><input name="stripeAccountId" className="field font-mono" defaultValue={program.stripeAccountId} placeholder="acct_..." autoComplete="off"/><small className="text-[var(--muted)]">Clear this field and save to remove the assignment.</small></label><button className="min-h-11 justify-self-start rounded-sm bg-[var(--maroon)] px-4 font-black uppercase text-white">Verify and save</button></form>)}</div></section> : null}

    <form action={updateMyPassword} className="wildcat-card grid gap-4 rounded-sm p-5"><div><p className="eyebrow">Your account</p><h2 className="text-2xl font-black uppercase text-[var(--ink)]">Change password</h2><p className="mt-1 text-sm font-medium text-[var(--muted)]">Signed in as {session.user.email}</p></div>{status.password === "changed" && <p role="status" className="rounded-sm bg-[#f1fbf3] p-3 font-black text-[#225c2d]">Password changed.</p>}<label className="grid gap-1"><span className="font-black uppercase">Current password</span><input name="currentPassword" type="password" className="field" required /></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1"><span className="font-black uppercase">New password</span><input name="newPassword" type="password" minLength={12} className="field" required /></label><label className="grid gap-1"><span className="font-black uppercase">Confirm password</span><input name="confirmPassword" type="password" minLength={12} className="field" required /></label></div><button className="min-h-12 rounded-sm bg-[var(--maroon)] px-5 font-black uppercase text-white">Update password</button></form>
  </div>;
}
